---
<% require 'json'
php_layer = JSON.parse(File.read('php.json'))
%>
driver:
  name: docker
  socket: tcp://192.168.59.103:2376

provisioner:
  name: chef_zero
  environment: test

platforms:
  - name: ubuntu-14.04
    driver_config:
      forward:
      - 80
suites:
  - name: default
    run_list:
     - opsworks_agent
     - mysql::client
     - dependencies
     - opsworks_ganglia::client
     - mod_php5_apache2
     - deploy::default
     - deploy::php
    attributes:  { "opsworks" : <%=php_layer['opsworks'].to_json%>, "deploy": <%=php_layer['deploy'].to_json%> } 
    cookbook_path: cookbooks
